export const ALLOWED_EXTENSIONS = ['srt', 'ass', 'ssa', 'vtt'] as const
export const MAX_CONTENT_LENGTH = 100 * 1024 * 1024 // 100 MB

export const LANGUAGE_NAMES: Record<string, string> = {
  en: 'angielski',
  pl: 'polski',
  de: 'niemiecki',
  fr: 'francuski',
  es: 'hiszpański',
  it: 'włoski',
  ru: 'rosyjski',
  uk: 'ukraiński',
  cs: 'czeski',
  sk: 'słowacki',
  zh: 'chiński',
  ja: 'japoński',
  ko: 'koreański',
  ar: 'arabski',
  pt: 'portugalski',
  nl: 'holenderski',
  sv: 'szwedzki',
  no: 'norweski',
  da: 'duński',
  fi: 'fiński',
  tr: 'turecki',
}

export const DEEPL_LANG_MAP: Record<string, string> = {
  en: 'EN',
  pl: 'PL',
  de: 'DE',
  fr: 'FR',
  es: 'ES',
  it: 'IT',
  ru: 'RU',
  uk: 'UK',
  cs: 'CS',
  sk: 'SK',
  zh: 'ZH',
  ja: 'JA',
  ko: 'KO',
  ar: 'AR',
  pt: 'PT',
  nl: 'NL',
  sv: 'SV',
  no: 'NB',
  da: 'DA',
  fi: 'FI',
  tr: 'TR',
}

export const ENGINE_ICONS: Record<string, string> = {
  libretranslate: 'bi-globe',
  ollama: 'bi-robot',
  deeplx: 'bi-translate',
  deepseek: 'bi-cpu',
  openai: 'bi-bolt',
  anthropic: 'bi-brain',
  azure: 'bi-cloud',
  google: 'bi-google',
  googlegtx: 'bi-google',
  deepl: 'bi-rocket',
  custom: 'bi-code',
}